import WynnRegistrationsApp from "@app-types/WynnRegistrationsApp.types";

const phoneNumberLocals: WynnRegistrationsApp.PhoneNumberFieldData[] = [
  {
    code: "ad",
    flagImgSrc: "https://flagcdn.com/h40/ad.png",
    label: "Andorra",
    countryCode: "+376",
  },
  {
    code: "ae",
    flagImgSrc: "https://flagcdn.com/h40/ae.png",
    label: "United Arab Emirates",
    countryCode: "+971",
  },
  {
    code: "af",
    flagImgSrc: "https://flagcdn.com/h40/af.png",
    label: "Afghanistan",
    countryCode: "+93",
  },
  {
    code: "ag",
    flagImgSrc: "https://flagcdn.com/h40/ag.png",
    label: "Antigua and Barbuda",
    countryCode: "+1-268",
  },
  {
    code: "ai",
    flagImgSrc: "https://flagcdn.com/h40/ai.png",
    label: "Anguilla",
    countryCode: "+1-264",
  },
  {
    code: "al",
    flagImgSrc: "https://flagcdn.com/h40/al.png",
    label: "Albania",
    countryCode: "+355",
  },
  {
    code: "am",
    flagImgSrc: "https://flagcdn.com/h40/am.png",
    label: "Armenia",
    countryCode: "+374",
  },
  {
    code: "ao",
    flagImgSrc: "https://flagcdn.com/h40/ao.png",
    label: "Angola",
    countryCode: "+244",
  },
  {
    code: "aq",
    flagImgSrc: "https://flagcdn.com/h40/aq.png",
    label: "Antarctica",
    countryCode: "+672",
  },
  {
    code: "ar",
    flagImgSrc: "https://flagcdn.com/h40/ar.png",
    label: "Argentina",
    countryCode: "+54",
  },
  {
    code: "as",
    flagImgSrc: "https://flagcdn.com/h40/as.png",
    label: "American Samoa",
    countryCode: "+1-684",
  },
  {
    code: "at",
    flagImgSrc: "https://flagcdn.com/h40/at.png",
    label: "Austria",
    countryCode: "+43",
  },
  {
    code: "au",
    flagImgSrc: "https://flagcdn.com/h40/au.png",
    label: "Australia",
    countryCode: "+61",
  },
  {
    code: "aw",
    flagImgSrc: "https://flagcdn.com/h40/aw.png",
    label: "Aruba",
    countryCode: "+297",
  },
  {
    code: "ax",
    flagImgSrc: "https://flagcdn.com/h40/ax.png",
    label: "Åland Islands",
    countryCode: "+358",
  },
  {
    code: "az",
    flagImgSrc: "https://flagcdn.com/h40/az.png",
    label: "Azerbaijan",
    countryCode: "+994",
  },
  {
    code: "ba",
    flagImgSrc: "https://flagcdn.com/h40/ba.png",
    label: "Bosnia and Herzegovina",
    countryCode: "+387",
  },
  {
    code: "bb",
    flagImgSrc: "https://flagcdn.com/h40/bb.png",
    label: "Barbados",
    countryCode: "+1-246",
  },
  {
    code: "bd",
    flagImgSrc: "https://flagcdn.com/h40/bd.png",
    label: "Bangladesh",
    countryCode: "+880",
  },
  {
    code: "be",
    flagImgSrc: "https://flagcdn.com/h40/be.png",
    label: "Belgium",
    countryCode: "+32",
  },
  {
    code: "bf",
    flagImgSrc: "https://flagcdn.com/h40/bf.png",
    label: "Burkina Faso",
    countryCode: "+226",
  },
  {
    code: "bg",
    flagImgSrc: "https://flagcdn.com/h40/bg.png",
    label: "Bulgaria",
    countryCode: "+359",
  },
  {
    code: "bh",
    flagImgSrc: "https://flagcdn.com/h40/bh.png",
    label: "Bahrain",
    countryCode: "+973",
  },
  {
    code: "bi",
    flagImgSrc: "https://flagcdn.com/h40/bi.png",
    label: "Burundi",
    countryCode: "+257",
  },
  {
    code: "bj",
    flagImgSrc: "https://flagcdn.com/h40/bj.png",
    label: "Benin",
    countryCode: "+229",
  },
  {
    code: "bl",
    flagImgSrc: "https://flagcdn.com/h40/bl.png",
    label: "Saint Barthélemy",
    countryCode: "+590",
  },
  {
    code: "bm",
    flagImgSrc: "https://flagcdn.com/h40/bm.png",
    label: "Bermuda",
    countryCode: "+1-441",
  },
  {
    code: "bn",
    flagImgSrc: "https://flagcdn.com/h40/bn.png",
    label: "Brunei",
    countryCode: "+673",
  },
  {
    code: "bo",
    flagImgSrc: "https://flagcdn.com/h40/bo.png",
    label: "Bolivia",
    countryCode: "+591",
  },
  {
    code: "bq",
    flagImgSrc: "https://flagcdn.com/h40/bq.png",
    label: "Caribbean Netherlands",
    countryCode: "+599",
  },
  {
    code: "br",
    flagImgSrc: "https://flagcdn.com/h40/br.png",
    label: "Brazil",
    countryCode: "+55",
  },
  {
    code: "bs",
    flagImgSrc: "https://flagcdn.com/h40/bs.png",
    label: "Bahamas",
    countryCode: "+1-242",
  },
  {
    code: "bt",
    flagImgSrc: "https://flagcdn.com/h40/bt.png",
    label: "Bhutan",
    countryCode: "+975",
  },
  {
    code: "bv",
    flagImgSrc: "https://flagcdn.com/h40/bv.png",
    label: "Bouvet Island",
    countryCode: "+47",
  },
  {
    code: "bw",
    flagImgSrc: "https://flagcdn.com/h40/bw.png",
    label: "Botswana",
    countryCode: "+267",
  },
  {
    code: "by",
    flagImgSrc: "https://flagcdn.com/h40/by.png",
    label: "Belarus",
    countryCode: "+375",
  },
  {
    code: "bz",
    flagImgSrc: "https://flagcdn.com/h40/bz.png",
    label: "Belize",
    countryCode: "+501",
  },
  {
    code: "ca",
    flagImgSrc: "https://flagcdn.com/h40/ca.png",
    label: "Canada",
    countryCode: "+1",
  },
  {
    code: "cc",
    flagImgSrc: "https://flagcdn.com/h40/cc.png",
    label: "Cocos (Keeling) Islands",
    countryCode: "+61",
  },
  {
    code: "cd",
    flagImgSrc: "https://flagcdn.com/h40/cd.png",
    label: "DR Congo",
    countryCode: "+243",
  },
  {
    code: "cf",
    flagImgSrc: "https://flagcdn.com/h40/cf.png",
    label: "Central African Republic",
    countryCode: "+236",
  },
  {
    code: "cg",
    flagImgSrc: "https://flagcdn.com/h40/cg.png",
    label: "Republic of the Congo",
    countryCode: "+242",
  },
  {
    code: "ch",
    flagImgSrc: "https://flagcdn.com/h40/ch.png",
    label: "Switzerland",
    countryCode: "+41",
  },
  {
    code: "ci",
    flagImgSrc: "https://flagcdn.com/h40/ci.png",
    label: "Côte d'Ivoire (Ivory Coast)",
    countryCode: "+225",
  },
  {
    code: "ck",
    flagImgSrc: "https://flagcdn.com/h40/ck.png",
    label: "Cook Islands",
    countryCode: "+682",
  },
  {
    code: "cl",
    flagImgSrc: "https://flagcdn.com/h40/cl.png",
    label: "Chile",
    countryCode: "+56",
  },
  {
    code: "cm",
    flagImgSrc: "https://flagcdn.com/h40/cm.png",
    label: "Cameroon",
    countryCode: "+237",
  },
  {
    code: "cn",
    flagImgSrc: "https://flagcdn.com/h40/cn.png",
    label: "China",
    countryCode: "+86",
  },
  {
    code: "co",
    flagImgSrc: "https://flagcdn.com/h40/co.png",
    label: "Colombia",
    countryCode: "+57",
  },
  {
    code: "cr",
    flagImgSrc: "https://flagcdn.com/h40/cr.png",
    label: "Costa Rica",
    countryCode: "+506",
  },
  {
    code: "cu",
    flagImgSrc: "https://flagcdn.com/h40/cu.png",
    label: "Cuba",
    countryCode: "+53",
  },
  {
    code: "cv",
    flagImgSrc: "https://flagcdn.com/h40/cv.png",
    label: "Cape Verde",
    countryCode: "+238",
  },
  {
    code: "cw",
    flagImgSrc: "https://flagcdn.com/h40/cw.png",
    label: "Curaçao",
    countryCode: "+599",
  },
  {
    code: "cx",
    flagImgSrc: "https://flagcdn.com/h40/cx.png",
    label: "Christmas Island",
    countryCode: "+61",
  },
  {
    code: "cy",
    flagImgSrc: "https://flagcdn.com/h40/cy.png",
    label: "Cyprus",
    countryCode: "+357",
  },
  {
    code: "cz",
    flagImgSrc: "https://flagcdn.com/h40/cz.png",
    label: "Czechia",
    countryCode: "+420",
  },
  {
    code: "de",
    flagImgSrc: "https://flagcdn.com/h40/de.png",
    label: "Germany",
    countryCode: "+49",
  },
  {
    code: "dj",
    flagImgSrc: "https://flagcdn.com/h40/dj.png",
    label: "Djibouti",
    countryCode: "+253",
  },
  {
    code: "dk",
    flagImgSrc: "https://flagcdn.com/h40/dk.png",
    label: "Denmark",
    countryCode: "+45",
  },
  {
    code: "dm",
    flagImgSrc: "https://flagcdn.com/h40/dm.png",
    label: "Dominica",
    countryCode: "+1-767",
  },
  {
    code: "do",
    flagImgSrc: "https://flagcdn.com/h40/do.png",
    label: "Dominican Republic",
    countryCode: "+1-809, +1-829, +1-849",
  },
  {
    code: "dz",
    flagImgSrc: "https://flagcdn.com/h40/dz.png",
    label: "Algeria",
    countryCode: "+213",
  },
  {
    code: "ec",
    flagImgSrc: "https://flagcdn.com/h40/ec.png",
    label: "Ecuador",
    countryCode: "+593",
  },
  {
    code: "ee",
    flagImgSrc: "https://flagcdn.com/h40/ee.png",
    label: "Estonia",
    countryCode: "+372",
  },
  {
    code: "eg",
    flagImgSrc: "https://flagcdn.com/h40/eg.png",
    label: "Egypt",
    countryCode: "+20",
  },
  {
    code: "er",
    flagImgSrc: "https://flagcdn.com/h40/er.png",
    label: "Eritrea",
    countryCode: "+291",
  },
  {
    code: "es",
    flagImgSrc: "https://flagcdn.com/h40/es.png",
    label: "Spain",
    countryCode: "+34",
  },
  {
    code: "et",
    flagImgSrc: "https://flagcdn.com/h40/et.png",
    label: "Ethiopia",
    countryCode: "+251",
  },
  {
    code: "fi",
    flagImgSrc: "https://flagcdn.com/h40/fi.png",
    label: "Finland",
    countryCode: "+358",
  },
  {
    code: "fj",
    flagImgSrc: "https://flagcdn.com/h40/fj.png",
    label: "Fiji",
    countryCode: "+679",
  },
  {
    code: "fk",
    flagImgSrc: "https://flagcdn.com/h40/fk.png",
    label: "Falkland Islands",
    countryCode: "+500",
  },
  {
    code: "fm",
    flagImgSrc: "https://flagcdn.com/h40/fm.png",
    label: "Micronesia",
    countryCode: "+691",
  },
  {
    code: "fo",
    flagImgSrc: "https://flagcdn.com/h40/fo.png",
    label: "Faroe Islands",
    countryCode: "+298",
  },
  {
    code: "fr",
    flagImgSrc: "https://flagcdn.com/h40/fr.png",
    label: "France",
    countryCode: "+33",
  },
  {
    code: "ga",
    flagImgSrc: "https://flagcdn.com/h40/ga.png",
    label: "Gabon",
    countryCode: "+241",
  },
  {
    code: "gb",
    flagImgSrc: "https://flagcdn.com/h40/gb.png",
    label: "United Kingdom",
    countryCode: "+44",
  },
  {
    code: "gd",
    flagImgSrc: "https://flagcdn.com/h40/gd.png",
    label: "Grenada",
    countryCode: "+1-473",
  },
  {
    code: "ge",
    flagImgSrc: "https://flagcdn.com/h40/ge.png",
    label: "Georgia",
    countryCode: "+995",
  },
  {
    code: "gf",
    flagImgSrc: "https://flagcdn.com/h40/gf.png",
    label: "French Guiana",
    countryCode: "+594",
  },
  {
    code: "gg",
    flagImgSrc: "https://flagcdn.com/h40/gg.png",
    label: "Guernsey",
    countryCode: "+44-1481",
  },
  {
    code: "gh",
    flagImgSrc: "https://flagcdn.com/h40/gh.png",
    label: "Ghana",
    countryCode: "+233",
  },
  {
    code: "gi",
    flagImgSrc: "https://flagcdn.com/h40/gi.png",
    label: "Gibraltar",
    countryCode: "+350",
  },
  {
    code: "gl",
    flagImgSrc: "https://flagcdn.com/h40/gl.png",
    label: "Greenland",
    countryCode: "+299",
  },
  {
    code: "gm",
    flagImgSrc: "https://flagcdn.com/h40/gm.png",
    label: "Gambia",
    countryCode: "+220",
  },
  {
    code: "gn",
    flagImgSrc: "https://flagcdn.com/h40/gn.png",
    label: "Guinea",
    countryCode: "+224",
  },
  {
    code: "gp",
    flagImgSrc: "https://flagcdn.com/h40/gp.png",
    label: "Guadeloupe",
    countryCode: "+590",
  },
  {
    code: "gq",
    flagImgSrc: "https://flagcdn.com/h40/gq.png",
    label: "Equatorial Guinea",
    countryCode: "+240",
  },
  {
    code: "gr",
    flagImgSrc: "https://flagcdn.com/h40/gr.png",
    label: "Greece",
    countryCode: "+30",
  },
  {
    code: "gt",
    flagImgSrc: "https://flagcdn.com/h40/gt.png",
    label: "Guatemala",
    countryCode: "+502",
  },
  {
    code: "gu",
    flagImgSrc: "https://flagcdn.com/h40/gu.png",
    label: "Guam",
    countryCode: "+1-671",
  },
  {
    code: "gw",
    flagImgSrc: "https://flagcdn.com/h40/gw.png",
    label: "Guinea-Bissau",
    countryCode: "+245",
  },
  {
    code: "gy",
    flagImgSrc: "https://flagcdn.com/h40/gy.png",
    label: "Guyana",
    countryCode: "+592",
  },
  {
    code: "hk",
    flagImgSrc: "https://flagcdn.com/h40/hk.png",
    label: "Hong Kong",
    countryCode: "+852",
  },
  {
    code: "hm",
    flagImgSrc: "https://flagcdn.com/h40/hm.png",
    label: "Heard Island and McDonald Islands",
    countryCode: "+672",
  },
  {
    code: "hn",
    flagImgSrc: "https://flagcdn.com/h40/hn.png",
    label: "Honduras",
    countryCode: "+504",
  },
  {
    code: "hr",
    flagImgSrc: "https://flagcdn.com/h40/hr.png",
    label: "Croatia",
    countryCode: "+385",
  },
  {
    code: "ht",
    flagImgSrc: "https://flagcdn.com/h40/ht.png",
    label: "Haiti",
    countryCode: "+509",
  },
  {
    code: "hu",
    flagImgSrc: "https://flagcdn.com/h40/hu.png",
    label: "Hungary",
    countryCode: "+36",
  },
  {
    code: "id",
    flagImgSrc: "https://flagcdn.com/h40/id.png",
    label: "Indonesia",
    countryCode: "+62",
  },
  {
    code: "ie",
    flagImgSrc: "https://flagcdn.com/h40/ie.png",
    label: "Ireland",
    countryCode: "+353",
  },
  {
    code: "il",
    flagImgSrc: "https://flagcdn.com/h40/il.png",
    label: "Israel",
    countryCode: "+972",
  },
  {
    code: "im",
    flagImgSrc: "https://flagcdn.com/h40/im.png",
    label: "Isle of Man",
    countryCode: "+44-1624",
  },
  {
    code: "in",
    flagImgSrc: "https://flagcdn.com/h40/in.png",
    label: "India",
    countryCode: "+91",
  },
  {
    code: "io",
    flagImgSrc: "https://flagcdn.com/h40/io.png",
    label: "British Indian Ocean Territory",
    countryCode: "+246",
  },
  {
    code: "iq",
    flagImgSrc: "https://flagcdn.com/h40/iq.png",
    label: "Iraq",
    countryCode: "+964",
  },
  {
    code: "ir",
    flagImgSrc: "https://flagcdn.com/h40/ir.png",
    label: "Iran",
    countryCode: "+98",
  },
  {
    code: "is",
    flagImgSrc: "https://flagcdn.com/h40/is.png",
    label: "Iceland",
    countryCode: "+354",
  },
  {
    code: "it",
    flagImgSrc: "https://flagcdn.com/h40/it.png",
    label: "Italy",
    countryCode: "+39",
  },
  {
    code: "je",
    flagImgSrc: "https://flagcdn.com/h40/je.png",
    label: "Jersey",
    countryCode: "+44-1534",
  },
  {
    code: "jm",
    flagImgSrc: "https://flagcdn.com/h40/jm.png",
    label: "Jamaica",
    countryCode: "+1-876",
  },
  {
    code: "jo",
    flagImgSrc: "https://flagcdn.com/h40/jo.png",
    label: "Jordan",
    countryCode: "+962",
  },
  {
    code: "jp",
    flagImgSrc: "https://flagcdn.com/h40/jp.png",
    label: "Japan",
    countryCode: "+81",
  },
  {
    code: "ke",
    flagImgSrc: "https://flagcdn.com/h40/ke.png",
    label: "Kenya",
    countryCode: "+254",
  },
  {
    code: "kg",
    flagImgSrc: "https://flagcdn.com/h40/kg.png",
    label: "Kyrgyzstan",
    countryCode: "+996",
  },
  {
    code: "kh",
    flagImgSrc: "https://flagcdn.com/h40/kh.png",
    label: "Cambodia",
    countryCode: "+855",
  },
  {
    code: "ki",
    flagImgSrc: "https://flagcdn.com/h40/ki.png",
    label: "Kiribati",
    countryCode: "+686",
  },
  {
    code: "km",
    flagImgSrc: "https://flagcdn.com/h40/km.png",
    label: "Comoros",
    countryCode: "+269",
  },
  {
    code: "kn",
    flagImgSrc: "https://flagcdn.com/h40/kn.png",
    label: "Saint Kitts and Nevis",
    countryCode: "+1-869",
  },
  {
    code: "kp",
    flagImgSrc: "https://flagcdn.com/h40/kp.png",
    label: "North Korea",
    countryCode: "+850",
  },
  {
    code: "kr",
    flagImgSrc: "https://flagcdn.com/h40/kr.png",
    label: "South Korea",
    countryCode: "+82",
  },
  {
    code: "kw",
    flagImgSrc: "https://flagcdn.com/h40/kw.png",
    label: "Kuwait",
    countryCode: "+965",
  },
  {
    code: "ky",
    flagImgSrc: "https://flagcdn.com/h40/ky.png",
    label: "Cayman Islands",
    countryCode: "+1-345",
  },
  {
    code: "kz",
    flagImgSrc: "https://flagcdn.com/h40/kz.png",
    label: "Kazakhstan",
    countryCode: "+7",
  },
  {
    code: "la",
    flagImgSrc: "https://flagcdn.com/h40/la.png",
    label: "Laos",
    countryCode: "+856",
  },
  {
    code: "lb",
    flagImgSrc: "https://flagcdn.com/h40/lb.png",
    label: "Lebanon",
    countryCode: "+961",
  },
  {
    code: "lc",
    flagImgSrc: "https://flagcdn.com/h40/lc.png",
    label: "Saint Lucia",
    countryCode: "+1-758",
  },
  {
    code: "li",
    flagImgSrc: "https://flagcdn.com/h40/li.png",
    label: "Liechtenstein",
    countryCode: "+423",
  },
  {
    code: "lk",
    flagImgSrc: "https://flagcdn.com/h40/lk.png",
    label: "Sri Lanka",
    countryCode: "+94",
  },
  {
    code: "lr",
    flagImgSrc: "https://flagcdn.com/h40/lr.png",
    label: "Liberia",
    countryCode: "+231",
  },
  {
    code: "ls",
    flagImgSrc: "https://flagcdn.com/h40/ls.png",
    label: "Lesotho",
    countryCode: "+266",
  },
  {
    code: "lt",
    flagImgSrc: "https://flagcdn.com/h40/lt.png",
    label: "Lithuania",
    countryCode: "+370",
  },
  {
    code: "lu",
    flagImgSrc: "https://flagcdn.com/h40/lu.png",
    label: "Luxembourg",
    countryCode: "+352",
  },
  {
    code: "lv",
    flagImgSrc: "https://flagcdn.com/h40/lv.png",
    label: "Latvia",
    countryCode: "+371",
  },
  {
    code: "ly",
    flagImgSrc: "https://flagcdn.com/h40/ly.png",
    label: "Libya",
    countryCode: "+218",
  },
  {
    code: "ma",
    flagImgSrc: "https://flagcdn.com/h40/ma.png",
    label: "Morocco",
    countryCode: "+212",
  },
  {
    code: "mc",
    flagImgSrc: "https://flagcdn.com/h40/mc.png",
    label: "Monaco",
    countryCode: "+377",
  },
  {
    code: "md",
    flagImgSrc: "https://flagcdn.com/h40/md.png",
    label: "Moldova",
    countryCode: "+373",
  },
  {
    code: "me",
    flagImgSrc: "https://flagcdn.com/h40/me.png",
    label: "Montenegro",
    countryCode: "+382",
  },
  {
    code: "mf",
    flagImgSrc: "https://flagcdn.com/h40/mf.png",
    label: "Saint Martin",
    countryCode: "+590",
  },
  {
    code: "mg",
    flagImgSrc: "https://flagcdn.com/h40/mg.png",
    label: "Madagascar",
    countryCode: "+261",
  },
  {
    code: "mh",
    flagImgSrc: "https://flagcdn.com/h40/mh.png",
    label: "Marshall Islands",
    countryCode: "+692",
  },
  {
    code: "mk",
    flagImgSrc: "https://flagcdn.com/h40/mk.png",
    label: "North Macedonia",
    countryCode: "+389",
  },
  {
    code: "ml",
    flagImgSrc: "https://flagcdn.com/h40/ml.png",
    label: "Mali",
    countryCode: "+223",
  },
  {
    code: "mm",
    flagImgSrc: "https://flagcdn.com/h40/mm.png",
    label: "Myanmar (Burma)",
    countryCode: "+95",
  },
  {
    code: "mn",
    flagImgSrc: "https://flagcdn.com/h40/mn.png",
    label: "Mongolia",
    countryCode: "+976",
  },
  {
    code: "mo",
    flagImgSrc: "https://flagcdn.com/h40/mo.png",
    label: "Macau",
    countryCode: "+853",
  },
  {
    code: "mp",
    flagImgSrc: "https://flagcdn.com/h40/mp.png",
    label: "Northern Mariana Islands",
    countryCode: "+1-670",
  },
  {
    code: "mq",
    flagImgSrc: "https://flagcdn.com/h40/mq.png",
    label: "Martinique",
    countryCode: "+596",
  },
  {
    code: "mr",
    flagImgSrc: "https://flagcdn.com/h40/mr.png",
    label: "Mauritania",
    countryCode: "+222",
  },
  {
    code: "ms",
    flagImgSrc: "https://flagcdn.com/h40/ms.png",
    label: "Montserrat",
    countryCode: "+1-664",
  },
  {
    code: "mt",
    flagImgSrc: "https://flagcdn.com/h40/mt.png",
    label: "Malta",
    countryCode: "+356",
  },
  {
    code: "mu",
    flagImgSrc: "https://flagcdn.com/h40/mu.png",
    label: "Mauritius",
    countryCode: "+230",
  },
  {
    code: "mv",
    flagImgSrc: "https://flagcdn.com/h40/mv.png",
    label: "Maldives",
    countryCode: "+960",
  },
  {
    code: "mw",
    flagImgSrc: "https://flagcdn.com/h40/mw.png",
    label: "Malawi",
    countryCode: "+265",
  },
  {
    code: "mx",
    flagImgSrc: "https://flagcdn.com/h40/mx.png",
    label: "Mexico",
    countryCode: "+52",
  },
  {
    code: "my",
    flagImgSrc: "https://flagcdn.com/h40/my.png",
    label: "Malaysia",
    countryCode: "+60",
  },
  {
    code: "mz",
    flagImgSrc: "https://flagcdn.com/h40/mz.png",
    label: "Mozambique",
    countryCode: "+258",
  },
  {
    code: "na",
    flagImgSrc: "https://flagcdn.com/h40/na.png",
    label: "Namibia",
    countryCode: "+264",
  },
  {
    code: "nc",
    flagImgSrc: "https://flagcdn.com/h40/nc.png",
    label: "New Caledonia",
    countryCode: "+687",
  },
  {
    code: "ne",
    flagImgSrc: "https://flagcdn.com/h40/ne.png",
    label: "Niger",
    countryCode: "+227",
  },
  {
    code: "nf",
    flagImgSrc: "https://flagcdn.com/h40/nf.png",
    label: "Norfolk Island",
    countryCode: "+672",
  },
  {
    code: "ng",
    flagImgSrc: "https://flagcdn.com/h40/ng.png",
    label: "Nigeria",
    countryCode: "+234",
  },
  {
    code: "ni",
    flagImgSrc: "https://flagcdn.com/h40/ni.png",
    label: "Nicaragua",
    countryCode: "+505",
  },
  {
    code: "nl",
    flagImgSrc: "https://flagcdn.com/h40/nl.png",
    label: "Netherlands",
    countryCode: "+31",
  },
  {
    code: "no",
    flagImgSrc: "https://flagcdn.com/h40/no.png",
    label: "Norway",
    countryCode: "+47",
  },
  {
    code: "np",
    flagImgSrc: "https://flagcdn.com/h40/np.png",
    label: "Nepal",
    countryCode: "+977",
  },
  {
    code: "nr",
    flagImgSrc: "https://flagcdn.com/h40/nr.png",
    label: "Nauru",
    countryCode: "+674",
  },
  {
    code: "nu",
    flagImgSrc: "https://flagcdn.com/h40/nu.png",
    label: "Niue",
    countryCode: "+683",
  },
  {
    code: "nz",
    flagImgSrc: "https://flagcdn.com/h40/nz.png",
    label: "New Zealand",
    countryCode: "+64",
  },
  {
    code: "om",
    flagImgSrc: "https://flagcdn.com/h40/om.png",
    label: "Oman",
    countryCode: "+968",
  },
  {
    code: "pa",
    flagImgSrc: "https://flagcdn.com/h40/pa.png",
    label: "Panama",
    countryCode: "+507",
  },
  {
    code: "pe",
    flagImgSrc: "https://flagcdn.com/h40/pe.png",
    label: "Peru",
    countryCode: "+51",
  },
  {
    code: "pf",
    flagImgSrc: "https://flagcdn.com/h40/pf.png",
    label: "French Polynesia",
    countryCode: "+689",
  },
  {
    code: "pg",
    flagImgSrc: "https://flagcdn.com/h40/pg.png",
    label: "Papua New Guinea",
    countryCode: "+675",
  },
  {
    code: "ph",
    flagImgSrc: "https://flagcdn.com/h40/ph.png",
    label: "Philippines",
    countryCode: "+63",
  },
  {
    code: "pk",
    flagImgSrc: "https://flagcdn.com/h40/pk.png",
    label: "Pakistan",
    countryCode: "+92",
  },
  {
    code: "pl",
    flagImgSrc: "https://flagcdn.com/h40/pl.png",
    label: "Poland",
    countryCode: "+48",
  },
  {
    code: "pm",
    flagImgSrc: "https://flagcdn.com/h40/pm.png",
    label: "Saint Pierre and Miquelon",
    countryCode: "+508",
  },
  {
    code: "pn",
    flagImgSrc: "https://flagcdn.com/h40/pn.png",
    label: "Pitcairn Islands",
    countryCode: "+870",
  },
  {
    code: "pr",
    flagImgSrc: "https://flagcdn.com/h40/pr.png",
    label: "Puerto Rico",
    countryCode: "+1-787, +1-939",
  },
  {
    code: "ps",
    flagImgSrc: "https://flagcdn.com/h40/ps.png",
    label: "Palestine",
    countryCode: "+970",
  },
  {
    code: "pt",
    flagImgSrc: "https://flagcdn.com/h40/pt.png",
    label: "Portugal",
    countryCode: "+351",
  },
  {
    code: "pw",
    flagImgSrc: "https://flagcdn.com/h40/pw.png",
    label: "Palau",
    countryCode: "+680",
  },
  {
    code: "py",
    flagImgSrc: "https://flagcdn.com/h40/py.png",
    label: "Paraguay",
    countryCode: "+595",
  },
  {
    code: "qa",
    flagImgSrc: "https://flagcdn.com/h40/qa.png",
    label: "Qatar",
    countryCode: "+974",
  },
  {
    code: "re",
    flagImgSrc: "https://flagcdn.com/h40/re.png",
    label: "Réunion",
    countryCode: "+262",
  },
  {
    code: "ro",
    flagImgSrc: "https://flagcdn.com/h40/ro.png",
    label: "Romania",
    countryCode: "+40",
  },
  {
    code: "rs",
    flagImgSrc: "https://flagcdn.com/h40/rs.png",
    label: "Serbia",
    countryCode: "+381",
  },
  {
    code: "ru",
    flagImgSrc: "https://flagcdn.com/h40/ru.png",
    label: "Russia",
    countryCode: "+7",
  },
  {
    code: "rw",
    flagImgSrc: "https://flagcdn.com/h40/rw.png",
    label: "Rwanda",
    countryCode: "+250",
  },
  {
    code: "sa",
    flagImgSrc: "https://flagcdn.com/h40/sa.png",
    label: "Saudi Arabia",
    countryCode: "+966",
  },
  {
    code: "sb",
    flagImgSrc: "https://flagcdn.com/h40/sb.png",
    label: "Solomon Islands",
    countryCode: "+677",
  },
  {
    code: "sc",
    flagImgSrc: "https://flagcdn.com/h40/sc.png",
    label: "Seychelles",
    countryCode: "+248",
  },
  {
    code: "sd",
    flagImgSrc: "https://flagcdn.com/h40/sd.png",
    label: "Sudan",
    countryCode: "+249",
  },
  {
    code: "se",
    flagImgSrc: "https://flagcdn.com/h40/se.png",
    label: "Sweden",
    countryCode: "+46",
  },
  {
    code: "sg",
    flagImgSrc: "https://flagcdn.com/h40/sg.png",
    label: "Singapore",
    countryCode: "+65",
  },
  {
    code: "sh",
    flagImgSrc: "https://flagcdn.com/h40/sh.png",
    label: "Saint Helena",
    countryCode: "+290",
  },
  {
    code: "si",
    flagImgSrc: "https://flagcdn.com/h40/si.png",
    label: "Slovenia",
    countryCode: "+386",
  },
  {
    code: "sj",
    flagImgSrc: "https://flagcdn.com/h40/sj.png",
    label: "Svalbard and Jan Mayen",
    countryCode: "+47",
  },
  {
    code: "sk",
    flagImgSrc: "https://flagcdn.com/h40/sk.png",
    label: "Slovakia",
    countryCode: "+421",
  },
  {
    code: "sl",
    flagImgSrc: "https://flagcdn.com/h40/sl.png",
    label: "Sierra Leone",
    countryCode: "+232",
  },
  {
    code: "sm",
    flagImgSrc: "https://flagcdn.com/h40/sm.png",
    label: "San Marino",
    countryCode: "+378",
  },
  {
    code: "sn",
    flagImgSrc: "https://flagcdn.com/h40/sn.png",
    label: "Senegal",
    countryCode: "+221",
  },
  {
    code: "so",
    flagImgSrc: "https://flagcdn.com/h40/so.png",
    label: "Somalia",
    countryCode: "+252",
  },
  {
    code: "sr",
    flagImgSrc: "https://flagcdn.com/h40/sr.png",
    label: "Suriname",
    countryCode: "+597",
  },
  {
    code: "ss",
    flagImgSrc: "https://flagcdn.com/h40/ss.png",
    label: "South Sudan",
    countryCode: "+211",
  },
  {
    code: "st",
    flagImgSrc: "https://flagcdn.com/h40/st.png",
    label: "São Tomé and Príncipe",
    countryCode: "+239",
  },
  {
    code: "sv",
    flagImgSrc: "https://flagcdn.com/h40/sv.png",
    label: "El Salvador",
    countryCode: "+503",
  },
  {
    code: "sx",
    flagImgSrc: "https://flagcdn.com/h40/sx.png",
    label: "Sint Maarten",
    countryCode: "+1-721",
  },
  {
    code: "sy",
    flagImgSrc: "https://flagcdn.com/h40/sy.png",
    label: "Syria",
    countryCode: "+963",
  },
  {
    code: "sz",
    flagImgSrc: "https://flagcdn.com/h40/sz.png",
    label: "Eswatini",
    countryCode: "+268",
  },
  {
    code: "tc",
    flagImgSrc: "https://flagcdn.com/h40/tc.png",
    label: "Turks and Caicos Islands",
    countryCode: "+1-649",
  },
  {
    code: "td",
    flagImgSrc: "https://flagcdn.com/h40/td.png",
    label: "Chad",
    countryCode: "+235",
  },
  {
    code: "tf",
    flagImgSrc: "https://flagcdn.com/h40/tf.png",
    label: "French Southern Territories",
    countryCode: "+262",
  },
  {
    code: "tg",
    flagImgSrc: "https://flagcdn.com/h40/tg.png",
    label: "Togo",
    countryCode: "+228",
  },
  {
    code: "th",
    flagImgSrc: "https://flagcdn.com/h40/th.png",
    label: "Thailand",
    countryCode: "+66",
  },
  {
    code: "tj",
    flagImgSrc: "https://flagcdn.com/h40/tj.png",
    label: "Tajikistan",
    countryCode: "+992",
  },
  {
    code: "tk",
    flagImgSrc: "https://flagcdn.com/h40/tk.png",
    label: "Tokelau",
    countryCode: "+690",
  },
  {
    code: "tl",
    flagImgSrc: "https://flagcdn.com/h40/tl.png",
    label: "Timor-Leste",
    countryCode: "+670",
  },
  {
    code: "tm",
    flagImgSrc: "https://flagcdn.com/h40/tm.png",
    label: "Turkmenistan",
    countryCode: "+993",
  },
  {
    code: "tn",
    flagImgSrc: "https://flagcdn.com/h40/tn.png",
    label: "Tunisia",
    countryCode: "+216",
  },
  {
    code: "to",
    flagImgSrc: "https://flagcdn.com/h40/to.png",
    label: "Tonga",
    countryCode: "+676",
  },
  {
    code: "tr",
    flagImgSrc: "https://flagcdn.com/h40/tr.png",
    label: "Turkey",
    countryCode: "+90",
  },
  {
    code: "tt",
    flagImgSrc: "https://flagcdn.com/h40/tt.png",
    label: "Trinidad and Tobago",
    countryCode: "+1-868",
  },
  {
    code: "tv",
    flagImgSrc: "https://flagcdn.com/h40/tv.png",
    label: "Tuvalu",
    countryCode: "+688",
  },
  {
    code: "tz",
    flagImgSrc: "https://flagcdn.com/h40/tz.png",
    label: "Tanzania",
    countryCode: "+255",
  },
  {
    code: "ua",
    flagImgSrc: "https://flagcdn.com/h40/ua.png",
    label: "Ukraine",
    countryCode: "+380",
  },
  {
    code: "ug",
    flagImgSrc: "https://flagcdn.com/h40/ug.png",
    label: "Uganda",
    countryCode: "+256",
  },
  {
    code: "us",
    flagImgSrc: "https://flagcdn.com/h40/us.png",
    label: "United States",
    countryCode: "+1",
  },
  {
    code: "uy",
    flagImgSrc: "https://flagcdn.com/h40/uy.png",
    label: "Uruguay",
    countryCode: "+598",
  },
  {
    code: "uz",
    flagImgSrc: "https://flagcdn.com/h40/uz.png",
    label: "Uzbekistan",
    countryCode: "+998",
  },
  {
    code: "va",
    flagImgSrc: "https://flagcdn.com/h40/va.png",
    label: "Vatican City",
    countryCode: "+379",
  },
  {
    code: "vc",
    flagImgSrc: "https://flagcdn.com/h40/vc.png",
    label: "Saint Vincent and the Grenadines",
    countryCode: "+1-784",
  },
  {
    code: "ve",
    flagImgSrc: "https://flagcdn.com/h40/ve.png",
    label: "Venezuela",
    countryCode: "+58",
  },
  {
    code: "vg",
    flagImgSrc: "https://flagcdn.com/h40/vg.png",
    label: "British Virgin Islands",
    countryCode: "+1-284",
  },
  {
    code: "vi",
    flagImgSrc: "https://flagcdn.com/h40/vi.png",
    label: "U.S. Virgin Islands",
    countryCode: "+1-340",
  },
  {
    code: "vn",
    flagImgSrc: "https://flagcdn.com/h40/vn.png",
    label: "Vietnam",
    countryCode: "+84",
  },
  {
    code: "vu",
    flagImgSrc: "https://flagcdn.com/h40/vu.png",
    label: "Vanuatu",
    countryCode: "+678",
  },
  {
    code: "wf",
    flagImgSrc: "https://flagcdn.com/h40/wf.png",
    label: "Wallis and Futuna",
    countryCode: "+681",
  },
  {
    code: "ws",
    flagImgSrc: "https://flagcdn.com/h40/ws.png",
    label: "Samoa",
    countryCode: "+685",
  },
  {
    code: "xk",
    flagImgSrc: "https://flagcdn.com/h40/xk.png",
    label: "Kosovo",
    countryCode: "+383",
  },
  {
    code: "ye",
    flagImgSrc: "https://flagcdn.com/h40/ye.png",
    label: "Yemen",
    countryCode: "+967",
  },
  {
    code: "yt",
    flagImgSrc: "https://flagcdn.com/h40/yt.png",
    label: "Mayotte",
    countryCode: "+262",
  },
  {
    code: "za",
    flagImgSrc: "https://flagcdn.com/h40/za.png",
    label: "South Africa",
    countryCode: "+27",
  },
  {
    code: "zm",
    flagImgSrc: "https://flagcdn.com/h40/zm.png",
    label: "Zambia",
    countryCode: "+260",
  },
  {
    code: "zw",
    flagImgSrc: "https://flagcdn.com/h40/zw.png",
    label: "Zimbabwe",
    countryCode: "+263",
  },
];

export default phoneNumberLocals;
